# Generated by Django 5.0.1 on 2024-01-25 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.TextField(verbose_name='password')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompleteCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(default=False, max_length=15, verbose_name='cep')),
                ('cpf', models.CharField(default=False, max_length=11, verbose_name='cpf')),
                ('cidade', models.CharField(default=False, max_length=50, verbose_name='cidade')),
                ('estado', models.CharField(default=False, max_length=2, verbose_name='estado')),
                ('telefone', models.CharField(default=False, max_length=11, verbose_name='telefone')),
                ('nascimento', models.CharField(max_length=10, verbose_name='nascimento')),
                ('sobre', models.TextField(default=False, verbose_name='sobre')),
                ('profissao', models.CharField(max_length=50, verbose_name='profissao')),
                ('hobbie', models.CharField(max_length=50, verbose_name='hobbie')),
                ('idioma', models.CharField(choices=[('ingles', 'Inglês'), ('espanhol', 'Espanhol'), ('italiano', 'Italiano'), ('alemão', 'Alemão'), ('outro', 'Outro')], max_length=30, verbose_name='idioma')),
                ('proficiencia', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente')], default=False, max_length=20, verbose_name='Proficiência')),
                ('comidaf', models.CharField(max_length=50, verbose_name='comidaf')),
                ('bebida', models.CharField(max_length=50, verbose_name='bebida')),
                ('restricao', models.CharField(choices=[('gluten', 'Glúten'), ('lactose', 'Lactose'), ('vegano', 'Vegano'), ('vegetariano', 'Vegetariano'), ('outros', 'Outros')], max_length=30, verbose_name='restricao')),
                ('usuario', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
