# Generated by Django 5.0.1 on 2024-01-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='capital',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='cidade',
            name='codigo_uf',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='cidade',
            name='latitude',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='cidade',
            name='longitude',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
