# Generated by Django 5.0.1 on 2024-02-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completecadastro',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
