# Generated by Django 4.2.6 on 2024-01-30 17:29

import angeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='usuario',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='nome',
        ),
        migrations.AddField(
            model_name='evento',
            name='bebidas_oferecidas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bebidas Oferecidas'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cardapio',
            field=models.TextField(blank=True, null=True, verbose_name='Cardápio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='convidado_pode_trazer',
            field=models.BooleanField(default=False, verbose_name='Convidado pode trazer bebidas?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateField(default=angeline.models.Evento.default_data, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='evento',
            name='estilo',
            field=models.CharField(choices=[('janta', 'Janta'), ('almoco', 'Almoço'), ('city_tour_gastronomico', 'City Tour Gastronômico'), ('harmonizacao', 'Harmonização'), ('workshop_gastronomico', 'Workshop Gastronômico'), ('aula_pratica', 'Aula prática de Cozinha'), ('outro', 'Outro')], default='', max_length=30, verbose_name='Estilo de Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fotos',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='evento_fotos/', verbose_name='Fotos do Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario',
            field=models.TimeField(default=angeline.models.Evento.default_horario, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inclui_bebidas',
            field=models.BooleanField(default=False, verbose_name='Inclui Bebidas?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='Minha casa', max_length=255, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='evento',
            name='max_convidados',
            field=models.PositiveIntegerField(default=1, verbose_name='Máximo de Convidados'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tema',
            field=models.CharField(default='Sem tema', max_length=255, verbose_name='Tema da experiência'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_host',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Valor Host'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_manutencao_site',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor Manutenção do Site (%)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da experiência'),
        ),
    ]
