# Generated by Django 5.0.1 on 2024-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completecadastro',
            name='sobre',
            field=models.TextField(default='', max_length=359, verbose_name='sobre'),
        ),
    ]
