# Generated by Django 5.0.1 on 2024-02-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completecadastro',
            name='outra_restricao',
        ),
    ]
