# Generated by Django 4.2.5 on 2024-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cidade',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
