# Generated by Django 5.0.1 on 2024-02-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fotos',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/', verbose_name='Fotos do Evento'),
        ),
    ]
