<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-02-26 20:10
=======
# Generated by Django 5.0.1 on 2024-02-27 18:51
>>>>>>> dev-luana

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='area_gastronomia',
            field=models.CharField(choices=[('profissional', 'Profissional'), ('amador', 'Amante da Gastronomia')], default='Amante da Gastronomia', max_length=20, verbose_name='Profissional da Área ou Amante da Gastronomia'),
        ),
        migrations.AlterField(
            model_name='host',
            name='email_corp',
            field=models.EmailField(max_length=100, verbose_name='Email corporativo'),
        ),
        migrations.AlterField(
            model_name='host',
            name='frequencia_servicos',
            field=models.CharField(choices=[('diaria', 'Diariamente'), ('semanal', 'Semanalmente'), ('mensal', 'Mensalmente'), ('ocasional', 'Ocasionalmente')], default='Diariamente', max_length=20, verbose_name='Frequência de Disponibilização de Serviços'),
        ),
    ]
