# Generated by Django 5.0.1 on 2024-02-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estilo',
            field=models.CharField(choices=[('janta', 'Janta'), ('almoco', 'Almoço'), ('city tour gastronomico', 'City Tour Gastronômico'), ('harmonizacao', 'Harmonização'), ('workshop gastronomico', 'Workshop Gastronômico'), ('aula pratica', 'Aula prática de Cozinha'), ('outro', 'Outro')], default='', max_length=30, verbose_name='Estilo de Evento'),
        ),
    ]
