# Generated by Django 5.0.1 on 2024-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('evento', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
