# Generated by Django 5.0.1 on 2024-02-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0002_alter_evento_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completecadastro',
            name='foto',
            field=models.ImageField(max_length=255, null=True, upload_to='media/', verbose_name='foto-perfil'),
        ),
    ]
