# Generated by Django 5.0.1 on 2024-02-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0002_alter_completecadastro_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
