# Generated by Django 5.0.1 on 2024-01-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0002_remove_completecadastro_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='completecadastro',
            name='cep',
            field=models.CharField(default=False, max_length=15, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='completecadastro',
            name='cidade',
            field=models.CharField(default=False, max_length=50, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='completecadastro',
            name='cpf',
            field=models.CharField(default=False, max_length=11, verbose_name='cpf'),
        ),
        migrations.AddField(
            model_name='completecadastro',
            name='estado',
            field=models.CharField(default=False, max_length=2, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='completecadastro',
            name='telefone',
            field=models.CharField(default=False, max_length=11, verbose_name='telefone'),
        ),
    ]
