# Generated by Django 4.2.6 on 2024-01-30 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('angeline', '0002_rename_usuario_evento_host_remove_evento_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='host',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
