# Generated by Django 5.0.1 on 2024-01-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0002_alter_completecadastro_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completecadastro',
            name='idioma',
            field=models.CharField(choices=[('nenhuma', 'Nenhuma'), ('ingles', 'Inglês'), ('espanhol', 'Espanhol'), ('italiano', 'Italiano'), ('alemão', 'Alemão'), ('outro', 'Outro')], max_length=30, verbose_name='idioma'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='restricao',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('gluten', 'Glúten'), ('lactose', 'Lactose'), ('vegano', 'Vegano'), ('vegetariano', 'Vegetariano'), ('outros', 'Outros')], max_length=30, verbose_name='restricao'),
        ),
    ]
