# Generated by Django 5.0.1 on 2024-02-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0002_alter_evento_fotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='datas_nascimento_convidados',
        ),
        migrations.AddField(
            model_name='evento',
            name='vagas_disponiveis',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Vagas Disponíveis'),
        ),
    ]
