# Generated by Django 5.0.1 on 2024-01-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0003_alter_completecadastro_idioma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completecadastro',
            name='idioma',
            field=models.CharField(choices=[('nenhuma', 'Nenhum'), ('ingles', 'Inglês'), ('espanhol', 'Espanhol'), ('italiano', 'Italiano'), ('alemão', 'Alemão'), ('outro', 'Outro')], max_length=30, verbose_name='idioma'),
        ),
    ]
