# Generated by Django 5.0.1 on 2024-02-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0003_remove_agendamento_datas_nascimento_convidados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='restricao',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('gluten', 'Glúten'), ('lactose', 'Lactose'), ('vegano', 'Vegano'), ('vegetariano', 'Vegetariano'), ('carneporco', 'Carne de porco'), ('diabetes', 'Diabetes'), ('nozes', 'Nozes'), ('frutosmar', 'Frutos do mar'), ('soja', 'Soja'), ('kosher', 'Kosher'), ('halal', 'Halal'), ('outros', 'Outros')], default='Nenhum', max_length=30, verbose_name='restricao'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='restricao',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('gluten', 'Glúten'), ('lactose', 'Lactose'), ('vegano', 'Vegano'), ('vegetariano', 'Vegetariano'), ('carneporco', 'Carne de porco'), ('diabetes', 'Diabetes'), ('nozes', 'Nozes'), ('frutosmar', 'Frutos do mar'), ('soja', 'Soja'), ('kosher', 'Kosher'), ('halal', 'Halal'), ('outros', 'Outros')], max_length=30, verbose_name='restricao'),
        ),
    ]
