# Generated by Django 5.0.1 on 2024-02-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0003_alter_completecadastro_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='foto',
            field=models.ImageField(max_length=255, null=True, upload_to='media/', verbose_name='foto-host'),
        ),
    ]
