# Generated by Django 5.0.1 on 2024-01-23 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0003_customuser_cpf_customuser_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(default=False, max_length=11, validators=[django.core.validators.RegexValidator(message='O CPF deve ter 11 dígitos numéricos.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(),
        ),
    ]
