# Generated by Django 5.0.1 on 2024-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0003_completecadastro_cep_completecadastro_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completecadastro',
            name='proficiencia',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente')], default=False, max_length=20, verbose_name='Proficiência'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='idioma',
            field=models.CharField(choices=[('ingles', 'Inglês'), ('espanhol', 'Espanhol'), ('italiano', 'Italiano'), ('alemão', 'Alemão'), ('outro', 'Outro')], max_length=30, verbose_name='idioma'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='restricao',
            field=models.CharField(choices=[('gluten', 'Glúten'), ('lactose', 'Lactose'), ('vegano', 'Vegano'), ('vegetariano', 'Vegetariano'), ('outros', 'Outros')], max_length=30, verbose_name='restricao'),
        ),
    ]
