# Generated by Django 5.0.1 on 2024-01-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0003_alter_cidade_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='codigo_uf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
