# Generated by Django 5.0.1 on 2024-01-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0004_completecadastro_proficiencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100, verbose_name='Nome da Empresa/Marca/Apelido')),
                ('motivo', models.TextField(verbose_name='Motivo para ser um host')),
                ('area_gastronomia', models.CharField(choices=[('profissional', 'Profissional'), ('amador', 'Amante da Gastronomia')], max_length=20, verbose_name='Profissional da Área ou Amante da Gastronomia')),
                ('servicos', models.TextField(verbose_name='Serviços Disponíveis')),
                ('frequencia_servicos', models.CharField(choices=[('diaria', 'Diariamente'), ('semanal', 'Semanalmente'), ('mensal', 'Mensalmente'), ('ocasional', 'Ocasionalmente')], max_length=20, verbose_name='Frequência de Disponibilização de Serviços')),
                ('local_servico', models.CharField(max_length=100, verbose_name='Local de Serviço')),
                ('descricao_local', models.TextField(verbose_name='Descrição do Local de Serviço')),
            ],
        ),
    ]
