# Generated by Django 5.0.1 on 2024-01-31 16:31

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0004_alter_completecadastro_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completecadastro',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9),
        ),
    ]
