# Generated by Django 5.0.1 on 2024-02-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0004_alter_completecadastro_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='completecadastro',
            name='outra_restricao',
            field=models.CharField(default='', max_length=30, verbose_name='outra_restricao'),
        ),
    ]
