# Generated by Django 5.0.1 on 2024-01-26 15:24

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0004_completecadastro_proficiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completecadastro',
            name='cep',
            field=models.CharField(default='', max_length=15, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='cidade',
            field=models.CharField(default='', max_length=50, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='comidaf',
            field=models.CharField(max_length=50, verbose_name='comida'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='estado',
            field=models.CharField(default='', max_length=2, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='sobre',
            field=models.TextField(default='', verbose_name='sobre'),
        ),
        migrations.AlterField(
            model_name='completecadastro',
            name='telefone',
            field=models.CharField(default='', max_length=11, verbose_name='telefone'),
        ),
    ]
