# Generated by Django 5.0.1 on 2024-01-31 16:36

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0005_alter_completecadastro_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completecadastro',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14),
        ),
    ]
