# Generated by Django 5.0.1 on 2024-01-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0005_alter_completecadastro_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
                ('codigoCapital', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('codigoUf', models.IntegerField()),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angeline.estado')),
            ],
        ),
    ]
