# Generated by Django 5.0.1 on 2024-01-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0006_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
    ]
