# Generated by Django 5.0.1 on 2024-01-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0006_host_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='usuario',
        ),
    ]
