# Generated by Django 5.0.1 on 2024-01-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angeline', '0007_alter_completecadastro_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='completecadastro',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descrição'),
        ),
    ]
